AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
Parameters:
  Stage:
    Type: String
    Default: labs
  Log:
    Type: String
    Default: DEBUG
  RestApiPesaId:
    Type: String
  DaysLiveToReport:
    Type: Number
    Default: 15
  CorsOrigin:
    Type: String
    Default: https://pesalabs.uvilorapps.com
Resources:
  PesaReporteBuket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub bucket-${Stage}-uvilor-pesa-reportes
      LifecycleConfiguration:
        Rules:
          - Id: DeleteReportsPdf
            Status: Enabled
            ExpirationInDays: !Ref DaysLiveToReport
            Prefix: reports/pdf
      VersioningConfiguration:
        Status: Suspended

  CreatePdfReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/functions/pdf-report/handler.handler
      FunctionName: !Sub ${AWS::StackName}-create-pdf-report
      Runtime: nodejs22.x
      Timeout: 10
      Architectures:
        - arm64
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: 
                - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:pesas-lbd-peso-${Stage}-get-peso
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetBucketLocation
              Resource: !Join [ "/", [ !GetAtt PesaReporteBuket.Arn, "*" ] ]
            - Effect: Allow
              Action: s3:ListBucket
              Resource: !GetAtt PesaReporteBuket.Arn
      Environment:
        Variables:
          STAGE: !Ref Stage
          LOG: !Ref Log
          BUCKET_PESAS_REPORT: !Ref PesaReporteBuket
          LAMBDA_GET_PESOS: !Sub pesas-lbd-peso-${Stage}-get-peso
          CORS_ORIGIN: !Ref CorsOrigin
  CreatePdfReportLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 14
      LogGroupName: !Sub /aws/lambda/${CreatePdfReportFunction}
  CreatePdfReportResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiPesaId
      ParentId: !ImportValue
        Fn::Sub: ${Stage}RestApiPesaV1Reportes
      PathPart: pdf
  CreatePdfReportNameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApiPesaId
      ParentId: !Ref CreatePdfReportResource
      PathPart: '{nombre}'
  CreatePdfReportNameMethodGET:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiPesaId
      ResourceId: !Ref CreatePdfReportNameResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !ImportValue
        Fn::Sub: ${Stage}RestApiPesaAuthorizerId
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreatePdfReportFunction.Arn}/invocations
  CreatePdfReportNameMethodPOST:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiPesaId
      ResourceId: !Ref CreatePdfReportNameResource
      HttpMethod: POST
      AuthorizationType: CUSTOM
      AuthorizerId: !ImportValue
        Fn::Sub: ${Stage}RestApiPesaAuthorizerId
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreatePdfReportFunction.Arn}/invocations
  CreatePdfReportNameMethodOPTIONS:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiPesaId
      ResourceId: !Ref CreatePdfReportNameResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Origin: !Sub "'${CorsOrigin}'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true
  CreatePdfReportPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CreatePdfReportFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiPesaId}/*/*

  RestApiDeploymentPesasLbdCatalogo:
    Type: AWS::ApiGateway::Deployment
    DependsOn: RootGetMethod
    Properties:
      RestApiId: !Ref RestApiPesaId
      StageName: !Ref Stage
    DependsOn:
      - CreatePdfReportNameMethodGET
      - CreatePdfReportNameMethodPOST
      - CreatePdfReportNameMethodOPTIONS